spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/services_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  mvc:
    static-path-pattern:


mybatis:
  type-aliases-package: com.mysheng.office.model
  mapper-locations: classpath:mapper/**.xml
  config-location: classpath:mybatis-config.xml
server:
  port: 9090
  servlet:
    context-path: /office

logging:
  level:
   com.mysheng.office.mapper: trace



#UPLOAD_FILE_DIR: D:/image/
#UPLOAD_FILE_HOST: http://localhost:7041

#file.staticAccessPath: /api/**
#file.uploadFolder: d:image/

#spring.mvc.static-path-pattern: /static/**
# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#spring.resources.static-locations: d:image/
spring.mvc.static-path-pattern: /api/**
spring.resources.static-locations: file:D://image/

